Add padig:mediaMaster to Funnel Cake Solr indexing
tulibraries/funnel_cake_index pull request #16
Opened 2021-04-02 16:58 UTC by ebtoner

See https://github.com/tulibraries/aggregator_mdx/pull/204. New field mapped in transform, which we would like to display in Funnel Cake for QA. Once this is merged, I will add to the Blacklight controller.

2021-04-02 19:05 UTC, ebtoner commented
@dkinzer @nomadicoder Is there an issue with Travis CI here? I know we've been moving away from Travis to Circle CI over time. These tests don't seem to be completing...

2021-04-02 21:15 UTC, dkinzer approved these changes

2021-04-02 21:22 UTC, dkinzer commented
@ebtoner Sorry, I think travis is busted.  I need to move these to CircleCI. Will do that on Monday.

2021-04-05 13:19 UTC, dkinzer commented on lib/funnel_cake_index/indexer_config.rb
>            "svcs" => "http://rdfs.org/sioc/services"
@ebtoner this needs a comma here or it will fail.

2021-04-05 14:15 UTC, dkinzer requested changes
This is failing locally without the comma.

2021-04-05 16:21 UTC, dkinzer approved these changes

2021-04-05 16:21 UTC, merged